spring.application.name=Todo
spring.profiles.active=dev
server.port=8080
spring.web.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/todo
spring.datasource.username=postgres
spring.datasource.password=1231234
spring.jpa.show-sql=true
